---
- name: add latest LTS release
  raw: "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -"

- name: Install node and npm
  apt: 
    pkg:
      - build-essential
      - nodejs
      - git
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Clone the web server repository
  become_user: ubuntu
  git: repo=https://github.com/ErunaM/AWS-Full-Stack-Assignment.git dest={{ home_dir }}/{{ backend }} update=yes force=yes accept_hostkey=yes
  register: git_done

# Configure the Backend
- name: Install Express for Backend
  npm:
    name: express
    global: yes
    state: present
    path: "{{ home_dir }}/{{ backend }}"

- name: Run the node server
  shell: "(cd {{ home_dir }}/{{ backend }} ; node server.js > /dev/null 2>&1 &)"
  async: 10
  poll: 0

# Configure the Frontend
- name: Install React for Frontend
  npm:
    name: react
    global: yes
    state: present
    path: "{{ home_dir }}/{{ frontend }}"

- name: Install Serve for Frontend
  npm:
    name: serve
    global: yes
    state: present
    path: "{{ home_dir }}/{{ frontend }}"

- name: npm install
  npm: path="{{ home_dir }}/{{ frontend}}"

- name: Build the application
  become_user: ubuntu
  command: npm run build
  args:
    chdir: "{{ home_dir }}/{{ frontend }}"

- name: Run the node server
  shell: "(cd {{ home_dir }}/{{ frontend }} ; serve -s build -l 80 > /dev/null 2>&1 &)"
  async: 10
  poll: 0
  #command: serve -s build -l 80
  #args:
  #  chdir: "{{ home_dir }}/{{ webapp_name }}"
